# Generated by Django 2.2.1 on 2019-07-21 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
