# Generated by Django 2.2.1 on 2019-07-28 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_posts_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='next_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next', to='posts.Posts'),
        ),
        migrations.AddField(
            model_name='posts',
            name='previous_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prev', to='posts.Posts'),
        ),
    ]
